import type { ProjectSpec } from "@/types/spec"

// ─── CLAUDE.md Generator ──────────────────────────────────────────────────────
// This is the most critical file in the entire product.
// The quality of this output determines whether "continue" actually works.

export function generateClaudeMd(spec: ProjectSpec): string {
  const lines: string[] = []

  const push = (...args: string[]) => lines.push(...args)
  const section = (title: string) => push(`\n## ${title}\n`)
  const hr = () => push("\n---\n")

  // ── Header ──
  push(`# ${spec.name || "Untitled Project"}`)
  push(`> ${spec.tagline || "A project built with SpecForge"}`)
  push("")
  push(`**Generated by SpecForge** | spec version ${spec.version} | ${new Date(spec.updatedAt).toLocaleDateString()}`)
  hr()

  // ── What This Is ──
  section("What this is")
  push(spec.description || `A ${spec.type} application.`)
  push("")
  push(`**Project type:** ${spec.type}`)
  push(`**Language:** ${spec.stack.language}`)
  push(`**Framework:** ${spec.stack.frontend}`)
  push(`**Styling:** ${spec.stack.styling}`)
  push(`**Database:** ${spec.stack.database}${spec.stack.orm !== "none" ? ` (via ${spec.stack.orm})` : ""}`)
  push(`**Auth:** ${spec.stack.auth}`)
  push(`**Deploy target:** ${spec.stack.deployment}`)

  // ── Critical Rules ──
  section("Critical rules — read before writing a single line")
  push("These are non-negotiable. Do not deviate.")
  push("")
  push(`- **Language:** Always TypeScript. Never JavaScript. Strict mode on.`)
  push(`- **Env vars:** ${spec.conventions.envVarPattern}`)
  push(`- **Error handling:** ${spec.conventions.errorHandling}`)
  push(`- **Naming:** ${spec.conventions.namingConvention} for variables and functions`)
  push(`- **API responses:** Always use this shape: \`${spec.conventions.apiResponseShape}\``)
  push(`- **Testing:** ${spec.conventions.testingApproach}`)
  push(`- **Folder structure:** ${spec.conventions.folderStructure}`)
  push("")
  push("**Never:**")
  push("- Never use `any` type — use `unknown` and narrow it")
  push("- Never commit secrets — all sensitive values go in `.env.local`")
  push("- Never write raw SQL — use the ORM")
  push("- Never expose internal error details to the client")
  if (spec.outOfScope.length > 0) {
    push("")
    push("**Out of scope for this build — do not implement:**")
    spec.outOfScope.forEach((item) => push(`- ${item}`))
  }

  // ── Folder Structure ──
  section("Folder structure")
  push("```")
  push(generateFolderStructure(spec))
  push("```")

  // ── Build Order ──
  section("Build order")
  push("Build modules in this exact order. Complete each module fully before starting the next.")
  push("Each module has a dedicated prompt file in the `prompts/` folder.")
  push("")
  spec.buildOrder.forEach((module, i) => {
    push(`${i + 1}. **${module}** → see \`prompts/${module}.md\``)
  })

  // ── Features ──
  if (spec.features.length > 0) {
    section("Features to build")
    const must = spec.features.filter((f) => f.priority === "must")
    const should = spec.features.filter((f) => f.priority === "should")
    const could = spec.features.filter((f) => f.priority === "could")

    if (must.length > 0) {
      push("### Must have (build these, no exceptions)")
      must.forEach((f) => push(`- **${f.name}**: ${f.description}`))
    }
    if (should.length > 0) {
      push("\n### Should have (build if time/complexity allows)")
      should.forEach((f) => push(`- **${f.name}**: ${f.description}`))
    }
    if (could.length > 0) {
      push("\n### Could have (nice to have, skip if complex)")
      could.forEach((f) => push(`- **${f.name}**: ${f.description}`))
    }
  }

  // ── Data Model ──
  if (spec.entities.length > 0) {
    section("Data model")
    push(`Using **${spec.stack.orm}** with **${spec.stack.database}**.`)
    push("")
    spec.entities.forEach((entity) => {
      push(`### ${entity.name}`)
      if (entity.description) push(`${entity.description}`)
      push("")
      push("| Field | Type | Required | Notes |")
      push("|-------|------|----------|-------|")
      entity.fields.forEach((field) => {
        const notes = [
          field.unique ? "unique" : "",
          field.default ? `default: ${field.default}` : "",
          field.enumValues ? `enum: ${field.enumValues.join(", ")}` : "",
          field.notes || "",
        ]
          .filter(Boolean)
          .join(", ")
        push(`| ${field.name} | ${field.type} | ${field.required ? "yes" : "no"} | ${notes} |`)
      })
      if (entity.timestamps) push("\n_Includes `createdAt` and `updatedAt` timestamps._")
      if (entity.softDelete) push("\n_Includes `deletedAt` for soft deletion._")
      push("")
    })
  }

  // ── API Routes ──
  if (spec.routes.length > 0) {
    section("API routes")
    push(`All routes follow the response shape: \`${spec.conventions.apiResponseShape}\``)
    push("")
    push("| Method | Path | Auth | Description |")
    push("|--------|------|------|-------------|")
    spec.routes.forEach((route) => {
      const auth = route.auth ? (route.roles?.length ? route.roles.join(", ") : "required") : "public"
      push(`| \`${route.method}\` | \`${route.path}\` | ${auth} | ${route.description} |`)
    })
  }

  // ── Pages ──
  if (spec.pages.length > 0) {
    section("Pages")
    push("| Page | Path | Auth | Description |")
    push("|------|------|------|-------------|")
    spec.pages.forEach((page) => {
      push(`| ${page.name} | \`${page.path}\` | ${page.auth ? "required" : "public"} | ${page.description} |`)
    })
  }

  // ── Integrations ──
  if (spec.integrations.length > 0) {
    section("Third-party integrations")
    spec.integrations.forEach((integration) => {
      push(`### ${integration.name} (${integration.provider})`)
      push(`**Purpose:** ${integration.purpose}`)
      if (integration.envVars.length > 0) {
        push(`**Env vars required:** ${integration.envVars.map((v) => `\`${v}\``).join(", ")}`)
      }
      push("")
    })
  }

  // ── Env Vars ──
  if (spec.envVars.length > 0) {
    section("Environment variables")
    push("Create `.env.local` with these variables. All are validated in `lib/env.ts` using Zod.")
    push("")
    push("```env")
    spec.envVars.forEach((envVar) => {
      push(`# ${envVar.description}${!envVar.required ? " (optional)" : ""}`)
      push(`${envVar.key}=${envVar.example || ""}`)
    })
    push("```")
  }

  // ── How to proceed ──
  section("How to proceed")
  push("1. Read this entire file before writing any code.")
  push("2. Open `prompts/` and read the prompt for the current module.")
  push("3. Check `spec.json` for the complete machine-readable spec.")
  push("4. Build the current module completely — types, implementation, tests.")
  push("5. When done, confirm completion and move to the next module in the build order.")
  push("")
  push("**When you are ready, type `continue` and Claude will start with the first module.**")

  hr()
  push(`_Generated by SpecForge · spec.json is the source of truth · Do not edit this file manually_`)

  return lines.join("\n")
}

// ─── Folder Structure Generator ───────────────────────────────────────────────

function generateFolderStructure(spec: ProjectSpec): string {
  const isNextJs = spec.stack.frontend === "nextjs"
  const hasDb = spec.stack.database !== "none"
  const hasAuth = spec.stack.auth !== "none"

  const tree: string[] = []

  if (isNextJs) {
    tree.push("src/")
    tree.push("  app/                    # Next.js App Router")
    tree.push("    (auth)/               # Auth-required routes group")
    tree.push("    api/                  # API route handlers")

    if (spec.routes.length > 0) {
      const routeGroups = [...new Set(spec.routes.map((r) => r.path.split("/")[2]).filter(Boolean))]
      routeGroups.slice(0, 4).forEach((group) => {
        tree.push(`      ${group}/`)
        tree.push(`        route.ts`)
      })
    }

    tree.push("  components/")
    tree.push("    ui/                   # shadcn/ui base components")
    tree.push("    shared/               # Shared feature components")
    tree.push("  lib/")
    tree.push("    env.ts                # Zod-validated env vars")
    tree.push("    db.ts                 # Database client singleton")
    if (hasAuth) tree.push("    auth.ts               # Auth config and helpers")
    tree.push("    utils.ts              # Shared utilities")
    tree.push("  middleware/")
    tree.push("    error.ts              # Global error handler")
    tree.push("    auth.ts               # Auth middleware")

    if (hasDb && spec.stack.orm === "prisma") {
      tree.push("prisma/")
      tree.push("  schema.prisma         # Database schema")
      tree.push("  migrations/")
      tree.push("  seed.ts               # Database seed script")
    }

    tree.push("tests/")
    tree.push("  unit/                   # Vitest unit tests")
    tree.push("  e2e/                    # Playwright E2E tests")
    tree.push(".env.local                # Local env vars (never commit)")
    tree.push(".env.example              # Example env vars (safe to commit)")
    tree.push("CLAUDE.md                 # This file")
    tree.push("spec.json                 # Machine-readable project spec")
  }

  return tree.join("\n")
}
